@php
    use App\Support\Locales;

    $locale = app()->getLocale();
    $dir = Locales::dir($locale);
    $settings = app(App\Support\Settings::class);
@endphp
<!DOCTYPE html>
<html lang="{{ Locales::htmlLang($locale) }}" dir="{{ $dir }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- Staging must never be indexed (§16). --}}
    @if (app()->environment(['local', 'staging']))
        <meta name="robots" content="noindex, nofollow">
    @endif

    {{--
        One preloaded font only (§15.1). The Arabic display face is what the
        hero headline renders in, so it is the one that would otherwise cause
        a visible swap on the largest text on the page.
    --}}
    <link rel="preload" href="/fonts/SaudiWeb-Bold.woff2" as="font" type="font/woff2" crossorigin>

    {{--
        The browser icon.

        An upload from the panel wins, as it always did. Without one the site
        ships the set generated by scripts/make-favicons.mjs from the client's
        own icon, public/images/amadcraft.ico.

        There is no SVG any more. The artwork is a bitmap the client supplied,
        and a hand-drawn vector beside it would be a second icon that drifts
        from the first the moment either changes.

        The .ico is still listed last: a browser that finds no <link> asks for
        /favicon.ico by name, and the one in this repo was once a zero-byte
        file — which is what put a blank square in the tab to begin with.

        This block sits in the one shared template, so the public site in both
        languages, the panel, the sign-in screen and every error page inherit
        it without repeating it.
    --}}
    @if ($favicon = app(App\Support\Brand::class)->url('favicon'))
        <link rel="icon" href="{{ $favicon }}">
    @else
        <link rel="icon" href="/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="icon" href="/favicon.ico" sizes="48x48">
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180">
    @endif

    <link rel="manifest" href="/site.webmanifest">
    <meta name="theme-color" content="#002546">

    {{-- Head tags rendered by Inertia (title, description, canonical, hreflang). --}}
    @inertiaHead

    {{--
        Structured data (§13), emitted here rather than from the Vue <Head>.

        Inertia's head manager handles title, meta, link and base — it drops a
        <script> silently, which is how this shipped as an empty tag once. The
        JSON is already built server-side by SchemaBuilder and arrives on the
        page object, so rendering it in Blade is both simpler and immune to
        that limitation. `<` is escaped inside the JSON itself, so no value
        from the database can close this tag early.
    --}}
    @if ($schema = data_get($page, 'props.seo.schema'))
        <script type="application/ld+json">{!! $schema !!}</script>
    @endif

    {{--
        Google Search Console ownership verification (§14.1). The client pastes
        only the content value from Search Console's HTML-tag method; the tag
        itself is built here so they cannot paste a malformed one.
    --}}
    @if ($verification = $settings->get('tracking.search_console'))
        <meta name="google-site-verification" content="{{ $verification }}">
    @endif

    @vite(['resources/css/app.css', 'resources/js/app.js'])

    {{--
        Google Tag Manager. The container ID is a client-managed setting, never
        a constant in code (§14.1, §22.9). Absent ID = no tag, no console error.
    --}}
    @if ($gtm = $settings->get('tracking.gtm_id'))
        <script>
            window.dataLayer = window.dataLayer || [];
        </script>
        <script async src="https://www.googletagmanager.com/gtm.js?id={{ $gtm }}"></script>
    @endif
</head>
<body>
    {{-- Keyboard users reach the content without tabbing the whole header (§10.8). --}}
    <a class="skip-link" href="#main">{{ __('common.skip_to_content') }}</a>

    @if ($gtm = $settings->get('tracking.gtm_id'))
        <noscript>
            <iframe src="https://www.googletagmanager.com/ns.html?id={{ $gtm }}"
                    height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>
    @endif

    @inertia
</body>
</html>
