@php
    use App\Support\Locales;

    $locale = app()->getLocale();
    $dir = Locales::dir($locale);
    $settings = app(App\Support\Settings::class);
    $palette = app(App\Support\Palette::class);
@endphp
<!DOCTYPE html>
<html lang="{{ Locales::htmlLang($locale) }}" dir="{{ $dir }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- Staging must never be indexed (§16). --}}
    @if (app()->environment(['local', 'staging']))
        <meta name="robots" content="noindex, nofollow">
    @endif

    {{--
        One preloaded font only (§15.1). The Arabic display face is what the
        hero headline renders in, so it is the one that would otherwise cause
        a visible swap on the largest text on the page.
    --}}
    <link rel="preload" href="/fonts/SaudiWeb-Bold.woff2" as="font" type="font/woff2" crossorigin>

    {{--
        The browser icon.

        An upload from the panel wins, as it always did. Without one the site
        ships the set generated by scripts/make-favicons.mjs from the client's
        own icon, public/images/amadcraft.ico.

        There is no SVG any more. The artwork is a bitmap the client supplied,
        and a hand-drawn vector beside it would be a second icon that drifts
        from the first the moment either changes.

        The .ico is still listed last: a browser that finds no <link> asks for
        /favicon.ico by name, and the one in this repo was once a zero-byte
        file — which is what put a blank square in the tab to begin with.

        This block sits in the one shared template, so the public site in both
        languages, the panel, the sign-in screen and every error page inherit
        it without repeating it.
    --}}
    @if ($favicon = app(App\Support\Brand::class)->url('favicon'))
        <link rel="icon" href="{{ $favicon }}">
    @else
        <link rel="icon" href="/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="icon" href="/favicon.ico" sizes="48x48">
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180">
    @endif

    <link rel="manifest" href="/site.webmanifest">

    {{-- The browser chrome takes the dominant colour, whatever it now is. --}}
    <meta name="theme-color" content="{{ $palette->themeColor() }}">

    {{-- Head tags rendered by Inertia (title, description, canonical, hreflang). --}}
    @inertiaHead

    {{--
        Structured data (§13), emitted here rather than from the Vue <Head>.

        Inertia's head manager handles title, meta, link and base — it drops a
        <script> silently, which is how this shipped as an empty tag once. The
        JSON is already built server-side by SchemaBuilder and arrives on the
        page object, so rendering it in Blade is both simpler and immune to
        that limitation. `<` is escaped inside the JSON itself, so no value
        from the database can close this tag early.
    --}}
    @if ($schema = data_get($page, 'props.seo.schema'))
        <script type="application/ld+json">{!! $schema !!}</script>
    @endif

    {{--
        Google Search Console ownership verification (§14.1). The client pastes
        only the content value from Search Console's HTML-tag method; the tag
        itself is built here so they cannot paste a malformed one.
    --}}
    @if ($verification = $settings->get('tracking.search_console'))
        <meta name="google-site-verification" content="{{ $verification }}">
    @endif

    @vite(['resources/css/app.css', 'resources/js/app.js'])

    {{--
        The client's colours.

        The four identity colours and the ten shades derived from them, as a
        `:root` block. It sits AFTER @vite deliberately: tokens.css ships the
        approved identity as its defaults, and this overrides them at equal
        specificity by coming later.

        Here rather than in a stylesheet because the values are a database
        row, and here rather than in JavaScript because a theme applied after
        hydration is a theme the visitor watches change — and would leave SSR,
        which the brief makes non-negotiable, rendering the wrong palette. In
        Blade it is correct in the first paint, on the public site, the panel,
        the sign-in screen and the error pages alike, because they all share
        this template.

        Palette::css() emits only values matching a hex or an `r g b` triplet,
        so nothing a client can type into the colour field can close this tag
        or add a declaration of its own.
    --}}
    <style id="brand-palette">{!! $palette->css() !!}</style>

    {{--
        Google Tag Manager. The container ID is a client-managed setting, never
        a constant in code (§14.1, §22.9). Absent ID = no tag, no console error.
    --}}
    @if ($gtm = $settings->get('tracking.gtm_id'))
        <script>
            window.dataLayer = window.dataLayer || [];
        </script>
        <script async src="https://www.googletagmanager.com/gtm.js?id={{ $gtm }}"></script>
    @endif

    {{--
        The other three the panel asks for (§14.1).

        These fields existed on the tracking screen, with placeholders and
        validation patterns, and nothing rendered them. An operator pasted a
        GA4 id, saw it save, and got no analytics — the panel promised an
        integration it did not perform, and said nothing. A dead field is worse
        than an absent one, because it is believed.

        ⚠️ DO NOT ALSO ADD THESE AS TAGS INSIDE GTM. Either place works; both
        together fire twice and every figure doubles. The panel is the simpler
        of the two for someone who is not a tag manager, so it is wired here —
        anyone who prefers to manage them in GTM should leave these three blank
        rather than fill them in as well.
    --}}
    @if ($ga4 = $settings->get('tracking.ga4_id'))
        <script async src="https://www.googletagmanager.com/gtag/js?id={{ $ga4 }}"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', @json($ga4));
        </script>
    @endif

    @if ($pixel = $settings->get('tracking.meta_pixel_id'))
        <script>
            !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
            n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
            document,'script','https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', @json($pixel));
            fbq('track', 'PageView');
        </script>
    @endif

    @if ($clarity = $settings->get('tracking.clarity_id'))
        <script>
            (function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", @json($clarity));
        </script>
    @endif
</head>
<body>
    {{-- Keyboard users reach the content without tabbing the whole header (§10.8). --}}
    <a class="skip-link" href="#main">{{ __('common.skip_to_content') }}</a>

    @if ($gtm = $settings->get('tracking.gtm_id'))
        <noscript>
            <iframe src="https://www.googletagmanager.com/ns.html?id={{ $gtm }}"
                    height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>
    @endif

    @inertia
</body>
</html>
